### ISSUE TITLE
Fix ble_temp example

### ISSUE THREAD

**Issue by adamgarbo** [sparkfun/MicroMod_Processor_Board-nRF52840#2]
Hi folks,

A quick heads up that the "ble_temp" example is missing `Wire.begin();`. This prevents the I2C bus/BME280 from initializing and causes the code to freeze after the BLE is initialized. Once added, the code works as intended.

Related forum post: https://forum.sparkfun.com/viewtopic.php?f=182&t=55165

Cheers,
Adam

**Comment by AndyEngland521** [comment]
Good catch @adamgarbo
