### ISSUE TITLE
more changes needed to compile on version 3.0

### ISSUE THREAD

**Issue by paulvha** [sparkfun/MicroMod_Processor_Board-nRF52840#5]
Compiling the MM nRF52840 will fail on Arduino library version 3.0.
 
Not only the softfp errors, as mentioned in the other issue, but also other errors. This Sparkfun add-in for the MBED-nano library needs to be updated

see https://forum.sparkfun.com/viewtopic.php?f=182&t=57407&p=232189#p232189 for details and changes to be made

regards,
Paul

**Comment by makin-stuff** [comment]
Hi there @paulvha. Thank you for updating us. I will look into these issues with the mbed core sometime this week.

**Comment by paulvha** [comment]
Thanks. The issues are not caused by Mbed, They are caused by changes in the Arduino Library folder structure and new  paramaters.
regards,
Paul

**Comment by makin-stuff** [comment]
Hi there @paulvha . 

I've updated the boards.txt and SF_MM_nRF52840_PB files like you've outlined in the forum post to be compatible with the "Arduino Mbed OS Nano Boards" v3.0.1. I've tested these changes on my personal hardware.

 I'm closing this issue for now, but if you try these files out and they don't work for some reason, please open up another issue on this repo. I will work to get the documentation associated with this product updated as well.

Thanks!
