### ISSUE TITLE
ArduinoBLE fails to compile on nrf52480

### ISSUE THREAD

**Issue by paulvha** [sparkfun/MicroMod_Processor_Board-nRF52840#6]
Based on a post on the SparkFun forum https://forum.sparkfun.com/viewtopic.php?f=182&t=57779, I looked into this problem.

**Error description**
Any ArduinoBLE example (e.g. Batterymonitor) will fail as it can not find references to certain routines. 

C:\Users\hk\AppData\Local\Temp\arduino_build_501413\libraries\ArduinoBLE-1.2.2\utility\HCICordioTransport.cpp.o: In function `HCICordioTransportClass::end()':
C:\Users\hk\Documents\Arduino\libraries\ArduinoBLE-1.2.2\src\utility/HCICordioTransport.cpp:237: undefined reference to `ble::CordioHCIDriver::terminate()'
C:\Users\hk\AppData\Local\Temp\arduino_build_501413\libraries\ArduinoBLE-1.2.2\utility\HCICordioTransport.cpp.o: In function `HCICordioTransportClass::begin()':
C:\Users\hk\Documents\Arduino\libraries\ArduinoBLE-1.2.2\src\utility/HCICordioTransport.cpp:215: undefined reference to `ble::CordioHCIDriver::initialize()'
C:\Users\hk\Documents\Arduino\libraries\ArduinoBLE-1.2.2\src\utility/HCICordioTransport.cpp:69: undefined reference to `ble::CordioHCITransportDriver::set_data_received_handler(void (*)(unsigned char*, unsigned char))'

**Root cause**

The libmbed.a  that Sparkfun provides with the variant is using the OLD namespace definition for BLE. The BLE namespace has structure has changed starting Mbed 6.2.1. Arduino is using an Mbed 6 later version than 6.2.1

**Solution**

In the Mbed files in 6.2.0 or before:
CordioHCIDriver.cpp
CordioHCIDriver.h
CordioHCITransportDriver.h
CordioHCITransportDriver.cpp

These files are located  in the folder : mbed-os/features/FEATURE_BLE/targets/TARGET_CORDIO/driver

The namespace definition needs to be changed from :

```
namespace ble {
namespace vendor { 
namespace cordio { 
```
to 

`namespace ble {`

Next to that it will need changes in different files for the nrf52480 Bluetooth target for using the right namespaces : e.g.

using namespace ble::vendor::ambiq_micro;
using namespace ble::vendor::cordio;

A new libmbed.a needs to be created and provided. This will apply to all the nrf52480 that are add-on to the Arduino Nano-Mbed.

Just a thought:
Given that Arduino is making regular changes to their Nano-mbed library and it is hard to keep up with that, wouldn't it be better to take the same approach as Artemis/Apollo3 and provide a single complete library package with Mbed where Sparkfun controls the all the changes?

regards,
Paul

**Comment by makin-stuff** [comment]
Hi there @paulvha. Thank you for reporting this problem on our repo. Good catch with the Arduino boards update!

The libmbed.a file is a copy from the "ARDUINO_NANO33BLE" variant. We've updated the [hookup guide](https://learn.sparkfun.com/tutorials/micromod-nrf52840-processor-hookup-guide/arduino-software-setup) to advise customers to duplicate that folder, rename it, and then copy over the unique files from this repo (variant.cpp, pins_ardhuino.h, and boards.txt) in hopes that this would mitigate compilation errors as the arduino package gets updated.

Unfortunately, at this time there is no planned effort to support the MM nRF52840 PB in the same manner we support the Artemis module.

Thanks again for your time and effort!
